<?php

// Add, remove, or reorder closeout products in this list.
return [
    [
        'section_heading' => 'Our Best-Selling Closeout Pianos',
        'title' => '1. Kawai Concert Grand',
        'price_condition' => '$17,995',
        'description' => 'A Masterpiece for Professionals|This stunning Kawai Concert Grand is a showstopper, perfect for professional musicians and serious enthusiasts. With its rich tonal quality and exceptional craftsmanship, this grand piano delivers an unparalleled musical experience. Whether you’re performing at a concert or enjoying a solo session at home, this elegant instrument is designed to inspire.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'image' => '/wp-content/uploads/2025/02/Kawai-2.jpg',
        'image_alt' => 'Kawai Concert Grand piano',
    ],
    [
        'title' => '2. Kawai Diapason Grand 6’1”',
        'price_condition' => '$4,999',
        'description' => 'Sophistication and Performance Combined|The Kawai Diapason Grand is ideal for players seeking a versatile instrument with a beautiful, resonant sound. Its compact size makes it perfect for homes and studios in Olyphant, PA, while its classic design enhances any room’s aesthetic appeal. Don’t miss this chance to own a premium grand piano at an incredible price.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'image' => '/wp-content/uploads/2025/02/Screenshot-2025-02-21-090727.png',
        'image_alt' => 'Kawai Diapason Grand piano',
    ],
    [
        'title' => '3. Baldwin Refurbished Model 243 (Year 2000)',
        'price_condition' => '$3,195',
        'description' => 'Timeless Craftsmanship, Refreshed for Modern Play|This refurbished Baldwin upright combines traditional elegance with modern functionality. It’s perfect for beginners and advanced players alike, offering a rich, expressive sound. Professionally restored and ready to play, this piano is a fantastic choice for families, music students, and anyone looking to add a touch of sophistication to their space.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
    ],
    [
        'section_heading' => 'Yamaha Workstations – Unmatched Creativity and Performance',
        'title' => 'Genos',
        'price_condition' => '$3,999 (New Open Box)',
        'description' => 'The Yamaha Genos is a top-of-the-line arranger workstation designed for professional musicians and composers. With its powerful sound engine, intuitive interface, and extensive creative features, the Genos is perfect for studio recording and live performances.',
        'availability' => 'Call Today',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'details_url' => 'https://usa.yamaha.com/products/musical_instruments/keyboards/arranger_workstations/genos/index.html',
        'details_label' => 'Discover the Genos',
    ],
    [
        'section_heading' => 'PSR-SX Series – Versatility Meets Affordability',
        'title' => 'PSR-SX900',
        'price_condition' => '$1,995 (Open Box, Free Shipping)',
        'description' => 'A powerful arranger keyboard with exceptional sound quality and a vast library of musical styles.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'image' => '/wp-content/uploads/2025/03/SX900_001_735x735_3e21ba69a60ae3bbe6fe817c0fcb6479-1.png',
        'image_alt' => 'Yamaha PSR-SX900 workstation keyboard',
    ],
    [
        'title' => 'PSR-SX700',
        'price_condition' => '$1,495 (Closeout)',
        'description' => 'Ideal for live performances and songwriting with a user-friendly interface.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'image' => '/wp-content/uploads/2025/03/SX700_001_735x735_bd3fa3e6bd6cc3f7e3fe78e9094643f9-1.png',
        'image_alt' => 'Yamaha PSR-SX700 workstation keyboard',
    ],
    [
        'title' => 'PSR-SX600',
        'price_condition' => '$995 (Closeout Open Box)',
        'description' => 'Perfect for hobbyists and beginners looking for a high-quality Yamaha keyboard at a great price.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'image' => '/wp-content/uploads/2025/03/SX600_004_735x735_423b6a368026770b624f5de21acf5f07-1.jpg',
        'image_alt' => 'Yamaha PSR-SX600 workstation keyboard',
    ],
    [
        'section_heading' => 'Clavinova Closeout Sale – Call for Special Pricing',
        'title' => 'CLP, CVP, and CSP Models',
        'price_condition' => 'Call for Special Pricing',
        'description' => 'All last year’s CLP, CVP, and CSP models are on sale! These digital pianos are perfect for home use, music education, and professional performances, offering realistic touch and sound with the latest digital technology.',
        'availability' => 'Limited Availability—Call Now',
        'phone' => '+15703525501',
        'phone_display' => '(570) 352-5501',
        'details_url' => '/contact-us/',
        'details_label' => 'Contact Us',
    ],
];
